# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a51b8722fd47ac7836a48d4f5abf0f2caa2fcc0ed66fb6fd518f8ce14c2ea23dcf6bdcf7f2ae38ee88d16ab7b4c1784583aa679c16cf4204094c9ac49f6da21a

test:
  secret_key_base: 153888aa950af3abb6d7e6f008c4551999da571acb80998dfe00f76725c3e05831e86c647fb5b699bca4a4a91640815beb7011065a57f29cd38a439355ec2db8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
